{
 "title": "AppBox Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "AppBox", "query": "label_values(appbox)" }
  ]
 },
 "panels": [
  {
   "title": "Days Till Next Payment",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bytesized_next_payment{appbox=\"$AppBox\"}"
    }
   ]
  },
  {
   "title": "AppBox Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "bytesized_disk_quota{appbox=\"$AppBox\"}",
     "legendFormat": "AppBox Disk Usage"
    }
   ]
  },
  {
   "title": "AppBox Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "bytesized_memory_usage{appbox=\"$AppBox\"}"
    }
   ]
  },
  {
   "title": "AppBox Bandwidth Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "bytesized_bandwidth_quota{appbox=\"$AppBox\"}",
     "legendFormat": "AppBox Bandwidth Usage"
    }
   ]
  }
 ]
}